#!/bin/bash
#Script  2: Package Check and Info
#Author: [UNNATI SINGH] | Course: Open Source Software
#Description: Checks if a specified package is installed on the system
#displays its details if installed and gives a brief description of the
#package using a case statement

#----Define a package to check----
PACKAGE = "mysql-server"      #change this to check other packages if needed


echo = "Checking Package: $PACKAGE"
#----checks if the package is installed----
#dpkg -l lists installed packages
#grep -q searches quietly (returns success/failure without printing)
if dpkg -l| grep -iq mysql; then
    echo "$PACKAGE is installed."
    #Display the package details (version , architecture , description)
    dpkg -l| grep -i mysql
else
    echo = "Package is NOT installed."
fi


#---provides package description using a case statement---
#Case statements allow checking multiple options for the same variable
case $PACKAGE in
    mysql-server) echo "MySQL: open-source database powering millions of apps";;
    apache2) echo "Apacheb: web servers that powers the internet";;
    vlc)echo"VLC: plays almost all media formats freely";;
    firefox)echo "Firefox:open-source browser for open web";;
    *)echo "Unknown Package";;
esac
