#!/bin/bash
# Script 3: Disk & Permission Audit Report
#Author: [UNNATI SINGH] | Course: Open Source Software
#Description: This script audits key linux directories for existence, permissions, ownerships
#and size. Additionally it checks the MySQL configuration directory. useful for understanding
#system organization and MySQL setup.

echo = "=============================================="
echo = " Disk and Permission Audit Report "
echo = "=============================================="

#---define directories to check ---
#list of important directories to audit
DIRS=("/etc" "/var/log" "/home" "/usr/bin" "/tmp")

#---Loop through h each directories--
for DIR in "${DIRS[@]}"; do
    echo " "
    echo "Checking: $DIR"
    #check if directory exists
    if [ -d "$DIR" ]; then
        PERMS=$(ls -ld $DIR | awk '{print $1}')
        OWNER=$(ls -ld $DIR | awk '{print $3}')
        GROUP=$(ls -ld $DIR | awk '{print $4}')
        #Display size of directory
        SIZE=$(du -sh $DIR 2>/dev/null | cut -f1)

        echo "Permissions : $PERMS"
        echo "Owner       : $OWNER"
        echo "Group       : $GROUP"
        echo "Size        : $SIZE"
    else
        echo "Directory does not exists"
    fi
done

echo " "
echo "=============================================="
echo "Checking MySQL Config Directory"
echo "=============================================="

CONFIG="/etc/mysql"

if [ -d "$CONFIG" ]; then
    ls -ld $CONFIG
else
    echo "MySQL config directory not found"
fi
