#!/bin/bash

#Script 1: System Identity Report
#Author: [UNNATI SINGH]
#Description: Displays basic system information for auditing purposes.
#This includes user details , home directory, kernel version, system uptime,
#current date and time

echo "==============================="
echo "Open Source Audit"
echo "==============================="

echo "Hello"

#-----shows the current logged-in user-----
#whoami prints the username of the user running the script
echo "User: $(whoami)"

#-----shows the home directory of the user-----
#'$HOME' is the environment variable storing the path to the users' home directory
echo "Home Directory: $HOME"

#-----shows the linux kernel version-----
# uname -r displays the currently running kernel version
echo "Kernel Version: $(uname -r)"

#-----shows the system uptime-----
#uptime -p prints how long the system has been running in a human readable format
echo "Uptime: $(uptime -p)"

#-----shows the current date and time-----
# $(date) displays the current date and time of system
echo "Date and Time: $(date)"

# --- Step 5: Show the current date and time ---
# 'date' displays the system's current date and time
echo "Date & Time: $(date)"
